
name: Trigger API

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  trigger-api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Start API server
      run: npm start

    - name: Send request to API
      run: |
        curl -X GET http://localhost:5000/config?APPLICATION=test&ENV_NAME=qa

